#!/usr/bin/env python3
"""Agentic fin-kit/fruit-thrower tool-build pipeline helper.

Consumes request JSON generated by mcp tool `request_tool_addition`.
Implements guarded triage, writes code to target module path, commits on `agent` branch.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path
from urllib.parse import quote

import requests

REPO = Path(__file__).resolve().parents[1]


def run(cmd: list[str], cwd: Path) -> None:
    subprocess.run(cmd, check=True, cwd=cwd)


def configure_authenticated_remote(repo_root: Path, repo_slug: str, token_env: str = "AGENT_GITHUB_TOKEN") -> bool:
    """Set authenticated HTTPS origin for push if token env is present."""
    token = os.environ.get(token_env, "").strip() or os.environ.get("AGENT_GITHUB_TOKEN", "").strip()
    if not token:
        return False

    owner, name = repo_slug.split("/", 1)
    encoded = quote(token, safe="")
    auth_url = f"https://{owner}:{encoded}@github.com/{owner}/{name}.git"
    run(["git", "remote", "set-url", "origin", auth_url], cwd=repo_root)
    return True


def configure_git_identity(repo_root: Path) -> None:
    """Ensure commits inside container have a deterministic identity."""
    name = os.environ.get("AGENT_GIT_USER_NAME", "finagent").strip()
    email = os.environ.get("AGENT_GIT_USER_EMAIL", "finagent@local").strip()
    run(["git", "config", "user.name", name], cwd=repo_root)
    run(["git", "config", "user.email", email], cwd=repo_root)


def triage(spec: dict) -> tuple[bool, str]:
    required = ["tool_name", "module_path", "summary", "code"]
    missing = [k for k in required if not str(spec.get(k, "")).strip()]
    if missing:
        return False, f"missing required fields: {', '.join(missing)}"
    if "subprocess" in spec["code"] or "os.system" in spec["code"]:
        return False, "unsafe process execution detected"

    # Normalize common user shorthand to the actual submodule path.
    mp = spec["module_path"].strip()
    if mp.startswith("fin_kit/"):
        mp = "fin-kit/" + mp[len("fin_kit/"):]
        spec["module_path"] = mp

    if not mp.startswith("fin-kit/"):
        return False, "module_path must be inside fin-kit/ so it gets indexed"

    return True, "viable"


def apply_changes(spec: dict, request_id: str, repo_root: Path, module_rel: str) -> None:
    target = repo_root / module_rel
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text("", encoding="utf-8")

    with target.open("a", encoding="utf-8") as f:
        f.write(f"\n\n# ---- agentic tool request {request_id} ----\n")
        f.write(spec["code"].rstrip() + "\n")

    req_log = repo_root / "AGENT_REQUESTS.md"
    with req_log.open("a", encoding="utf-8") as f:
        f.write(
            f"\n## {request_id}\n"
            f"- tool_name: `{spec['tool_name']}`\n"
            f"- module_path: `{module_rel}`\n"
            f"- summary: {spec['summary']}\n"
            f"- status: implemented on agent branch (pending PR review)\n"
        )


def maybe_create_pr(request_id: str, tool_name: str, repo_slug: str, base: str) -> str | None:
    token = os.environ.get("AGENT_GITHUB_TOKEN", "").strip()
    repo = repo_slug
    if not token:
        return None

    url = f"https://api.github.com/repos/{repo}/pulls"
    payload = {
        "title": f"agent: add {tool_name} ({request_id})",
        "head": "agent",
        "base": base,
        "body": (
            "Auto-generated by fruit-thrower tool builder.\n\n"
            f"Request ID: `{request_id}`\n"
            f"Tool: `{tool_name}`\n"
            "Please review code quality/tests/docs before merge."
        ),
    }
    r = requests.post(
        url,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
        json=payload,
        timeout=20,
    )
    if r.status_code in (200, 201):
        return r.json().get("html_url")

    # PR may already exist for agent->base
    if r.status_code == 422:
        q = requests.get(
            f"https://api.github.com/repos/{repo}/pulls?head={repo.split('/')[0]}:agent&base={base}&state=open",
            headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
            timeout=20,
        )
        if q.status_code == 200 and q.json():
            return q.json()[0].get("html_url")
    return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--request", required=True)
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()

    req_path = Path(args.request).resolve()
    spec = json.loads(req_path.read_text(encoding="utf-8"))
    request_id = spec.get("request_id", req_path.stem)

    ok, reason = triage(spec)
    report_dir = REPO / ".tool_builder" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{request_id}.json"

    report = {"viable": ok, "reason": reason, "request_id": request_id, "tool_name": spec.get("tool_name")}

    if not ok:
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"Rejected: {reason}")
        return

    module_path = spec["module_path"].strip()
    if module_path.startswith("fin-kit/"):
        repo_root = REPO / "fin-kit"
        module_rel = module_path[len("fin-kit/"):]
        repo_slug = os.environ.get("AGENT_GITHUB_REPO_FIN_KIT", "lakshya-aga/fin-kit").strip()
        pr_base = os.environ.get("AGENT_PR_BASE_FIN_KIT", "main").strip()
        token_env = "AGENT_GITHUB_TOKEN_FIN_KIT"
    else:
        repo_root = REPO
        module_rel = module_path
        repo_slug = os.environ.get("AGENT_GITHUB_REPO", "lakshya-aga/fruit-thrower").strip()
        pr_base = os.environ.get("AGENT_PR_BASE", "deploy").strip()
        token_env = "AGENT_GITHUB_TOKEN"

    run(["git", "checkout", "-B", "agent"], cwd=repo_root)
    configure_git_identity(repo_root)
    apply_changes(spec, request_id, repo_root=repo_root, module_rel=module_rel)
    run(["git", "add", module_rel, "AGENT_REQUESTS.md"], cwd=repo_root)
    run(["git", "commit", "-m", f"agent: implement requested function {spec['tool_name']} ({request_id})"], cwd=repo_root)
    used_auth_remote = False
    if args.push:
        used_auth_remote = configure_authenticated_remote(repo_root=repo_root, repo_slug=repo_slug, token_env=token_env)
        run(["git", "push", "-u", "origin", "agent"], cwd=repo_root)
        if used_auth_remote:
            run(["git", "remote", "set-url", "origin", f"https://github.com/{repo_slug}.git"], cwd=repo_root)

    auto_pr = os.environ.get("AGENT_AUTO_PR", "0") == "1"
    pr_url = maybe_create_pr(request_id, spec["tool_name"], repo_slug=repo_slug, base=pr_base) if (args.push and auto_pr) else None
    report["branch"] = "agent"
    report["repo"] = repo_slug
    report["pr_url"] = pr_url
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    if pr_url:
        print(f"PR: {pr_url}")
    else:
        print("Implemented on agent branch. Open PR for human approval.")


if __name__ == "__main__":
    main()
