#!/usr/bin/env python3
"""Agentic fin-kit/fruit-thrower tool-build pipeline helper.

Consumes request JSON generated by mcp tool `request_tool_addition`.
Implements guarded triage, writes code to target module path, commits on `agent` branch.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parents[1]


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, cwd=REPO)


def triage(spec: dict) -> tuple[bool, str]:
    required = ["tool_name", "module_path", "summary", "code"]
    missing = [k for k in required if not str(spec.get(k, "")).strip()]
    if missing:
        return False, f"missing required fields: {', '.join(missing)}"
    if "subprocess" in spec["code"] or "os.system" in spec["code"]:
        return False, "unsafe process execution detected"
    return True, "viable"


def apply_changes(spec: dict, request_id: str) -> None:
    target = REPO / spec["module_path"]
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text("", encoding="utf-8")

    with target.open("a", encoding="utf-8") as f:
        f.write(f"\n\n# ---- agentic tool request {request_id} ----\n")
        f.write(spec["code"].rstrip() + "\n")

    req_log = REPO / "AGENT_REQUESTS.md"
    with req_log.open("a", encoding="utf-8") as f:
        f.write(
            f"\n## {request_id}\n"
            f"- tool_name: `{spec['tool_name']}`\n"
            f"- module_path: `{spec['module_path']}`\n"
            f"- summary: {spec['summary']}\n"
            f"- status: implemented on agent branch (pending PR review)\n"
        )


def maybe_create_pr(request_id: str, tool_name: str) -> str | None:
    token = os.environ.get("AGENT_GITHUB_TOKEN", "").strip()
    repo = os.environ.get("AGENT_GITHUB_REPO", "lakshya-aga/fruit-thrower").strip()
    base = os.environ.get("AGENT_PR_BASE", "deploy").strip()
    if not token:
        return None

    url = f"https://api.github.com/repos/{repo}/pulls"
    payload = {
        "title": f"agent: add {tool_name} ({request_id})",
        "head": "agent",
        "base": base,
        "body": (
            "Auto-generated by fruit-thrower tool builder.\n\n"
            f"Request ID: `{request_id}`\n"
            f"Tool: `{tool_name}`\n"
            "Please review code quality/tests/docs before merge."
        ),
    }
    r = requests.post(
        url,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
        json=payload,
        timeout=20,
    )
    if r.status_code in (200, 201):
        return r.json().get("html_url")

    # PR may already exist for agent->base
    if r.status_code == 422:
        q = requests.get(
            f"https://api.github.com/repos/{repo}/pulls?head={repo.split('/')[0]}:agent&base={base}&state=open",
            headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
            timeout=20,
        )
        if q.status_code == 200 and q.json():
            return q.json()[0].get("html_url")
    return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--request", required=True)
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()

    req_path = Path(args.request).resolve()
    spec = json.loads(req_path.read_text(encoding="utf-8"))
    request_id = spec.get("request_id", req_path.stem)

    ok, reason = triage(spec)
    report_dir = REPO / ".tool_builder" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{request_id}.json"

    report = {"viable": ok, "reason": reason, "request_id": request_id, "tool_name": spec.get("tool_name")}

    if not ok:
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"Rejected: {reason}")
        return

    run(["git", "checkout", "-B", "agent"])
    apply_changes(spec, request_id)
    run(["git", "add", spec["module_path"], "AGENT_REQUESTS.md"])
    run(["git", "commit", "-m", f"agent: implement requested function {spec['tool_name']} ({request_id})"])
    if args.push:
        run(["git", "push", "-u", "origin", "agent"])

    pr_url = maybe_create_pr(request_id, spec["tool_name"]) if args.push else None
    report["branch"] = "agent"
    report["pr_url"] = pr_url
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    if pr_url:
        print(f"PR: {pr_url}")
    else:
        print("Implemented on agent branch. Open PR for human approval.")


if __name__ == "__main__":
    main()
